version: '2'
services:
  php:
    container_name: opencart_php
    build: ./php
    volumes:
      - ../upload:/var/www/html/
      - ./php/.bashrc:/root/.bashrc
      - ./php/.gitconfig:/root/.gitconfig
    depends_on:
      - mysql
  nginx:
    container_name: opencart_nginx
    image: nginx
    ports:
      - 8885:80
      - 8000:8000
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../upload:/var/www/html/
      - ../upload/system/storage/logs/:/var/log/nginx
    depends_on:
      - php
      - mysql

  mysql:
    container_name: opencart_mysql
    image: mysql:5.7.16
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=root